# Generated by Django 5.2.1 on 2025-05-15 12:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=cloudinary.models.CloudinaryField(default='memes/default.png', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatars/default.png', max_length=255, verbose_name='image'),
        ),
    ]
